#!/usr/bin/env python
"""
Copyright 2012 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class Category:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'items': 'list[Item]',
            'has_items': 'bool',
            'instructional_text': 'str',
            'category_images': 'list[CategoryImage]',
            'category_id': 'int',
            'has_subcategories': 'bool',
            'category_name': 'str'

        }


        self.items = None # list[Item]
        #Category has items
        self.has_items = None # bool
        #Instructional Text
        self.instructional_text = None # str
        self.category_images = None # list[CategoryImage]
        #Category ID
        self.category_id = None # int
        #Category has subcategories
        self.has_subcategories = None # bool
        #Category Name
        self.category_name = None # str
        
