#!/usr/bin/env python
"""
Copyright 2012 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class Item:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'item_modifiers': 'list[ItemModifier]',
            'name': 'str',
            'available_for_order': 'bool',
            'ticket_item_id': 'int',
            'price': 'float',
            'voided': 'bool',
            'item_id': 'int',
            'instructions': 'str',
            'quantity': 'int'

        }


        self.item_modifiers = None # list[ItemModifier]
        #Item Name
        self.name = None # str
        #Item still available to order
        self.available_for_order = None # bool
        #Ticket Item ID (This is specific to the ticket)
        self.ticket_item_id = None # int
        #Item Price
        self.price = None # float
        #Item is voided
        self.voided = None # bool
        #Item ID (This is specific to the item across tickets)
        self.item_id = None # int
        #Special Instructions
        self.instructions = None # str
        #Quantity of item
        self.quantity = None # int
        
