#!/usr/bin/env python
"""
Copyright 2012 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class Terminal:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'revenue_center_name': 'str',
            'default_device': 'bool',
            'terminal_id': 'int',
            'revenue_center_id': 'int',
            'ip_address': 'str',
            'name': 'str'

        }


        #Terminal Revenue Center name
        self.revenue_center_name = None # str
        #Is the default terminal
        self.default_device = None # bool
        #Terminal ID Number
        self.terminal_id = None # int
        #Terminal Revenue Center ID
        self.revenue_center_id = None # int
        #IP Address
        self.ip_address = None # str
        #Terminal Name
        self.name = None # str
        
