#!/usr/bin/env python
"""
Copyright 2012 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class User:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'first_name': 'str',
            'last_name': 'str',
            'middle_name': 'str',
            'dob': 'str',
            'email_address': 'str',
            'last_known_lon': 'float',
            'last_known_lat': 'float',
            'user_id': 'int',
            'cell_phone': 'str',
            'user_name': 'str'

        }


        #First Name
        self.first_name = None # str
        #Last Name
        self.last_name = None # str
        #Middle Name
        self.middle_name = None # str
        #Date of Birth
        self.dob = None # str
        #Email Address
        self.email_address = None # str
        #Last Known Longitude
        self.last_known_lon = None # float
        #Last Known Latitude
        self.last_known_lat = None # float
        #User ID
        self.user_id = None # int
        #Cell Phone
        self.cell_phone = None # str
        #User Name
        self.user_name = None # str
        
